"""Add audio 3D support and metadata tables

Revision ID: 25b67935f5e1
Revises:
Create Date: 2025-11-11 07:21:07.063486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25b67935f5e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create pgvector extension if not exists
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # Create enum type for ContentDomain
    contentdomain_enum = postgresql.ENUM('GENERAL', 'ADULT', 'MEDICAL', 'SPORTS', 'FASHION', 'EDUCATION', name='contentdomain')
    contentdomain_enum.create(op.get_bind())

    op.create_table('asset_3d_metadata',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('polygon_count', sa.Integer(), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('has_textures', sa.Boolean(), nullable=False),
    sa.Column('has_animations', sa.Boolean(), nullable=False),
    sa.Column('has_rigging', sa.Boolean(), nullable=False),
    sa.Column('has_materials', sa.Boolean(), nullable=False),
    sa.Column('material_count', sa.Integer(), nullable=True),
    sa.Column('texture_resolution', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('bounding_box_size', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('idx_3d_format', 'asset_3d_metadata', ['file_format'], unique=False)
    op.create_index('idx_3d_polygon_count', 'asset_3d_metadata', ['polygon_count'], unique=False)
    op.create_table('asset_adult_metadata',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('intensity_level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('tempo', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('scene_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('intimacy_level', sa.Integer(), nullable=True),
    sa.Column('body_parts_visible', sa.JSON(), nullable=True),
    sa.Column('clothing_state', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=True),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('lighting', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('idx_adult_intensity_tempo', 'asset_adult_metadata', ['intensity_level', 'tempo'], unique=False)
    op.create_index('idx_adult_intimacy', 'asset_adult_metadata', ['intimacy_level'], unique=False)
    op.create_index('idx_adult_scene_type', 'asset_adult_metadata', ['scene_type'], unique=False)
    op.create_table('asset_audio_metadata',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('codec', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('has_lyrics', sa.Boolean(), nullable=False),
    sa.Column('is_speech', sa.Boolean(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('idx_audio_codec', 'asset_audio_metadata', ['codec'], unique=False)
    op.create_index('idx_audio_sample_rate', 'asset_audio_metadata', ['sample_rate'], unique=False)
    op.create_index('idx_audio_speech', 'asset_audio_metadata', ['is_speech'], unique=False)
    op.create_table('asset_temporal_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('segment_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('objects', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('dominant_colors', sa.JSON(), nullable=True),
    sa.Column('camera_motion', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segment_asset_time', 'asset_temporal_segments', ['asset_id', 'timestamp_sec'], unique=False)
    op.create_index('idx_segment_type', 'asset_temporal_segments', ['asset_id', 'segment_type'], unique=False)
    op.create_index(op.f('ix_asset_temporal_segments_asset_id'), 'asset_temporal_segments', ['asset_id'], unique=False)
    op.add_column('assets', sa.Column('provider_uploads', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('assets', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assets', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('style_tags', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('assets', sa.Column('content_domain', sa.Enum('GENERAL', 'ADULT', 'MEDICAL', 'SPORTS', 'FASHION', 'EDUCATION', name='contentdomain'), nullable=False))
    op.add_column('assets', sa.Column('content_rating', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('assets', sa.Column('age_restricted', sa.Boolean(), nullable=False))
    op.add_column('assets', sa.Column('searchable', sa.Boolean(), nullable=False))
    op.add_column('assets', sa.Column('original_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assets', sa.Column('upload_method', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('assets', sa.Column('media_metadata', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('last_accessed_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_assets_age_restricted'), 'assets', ['age_restricted'], unique=False)
    op.create_index(op.f('ix_assets_content_domain'), 'assets', ['content_domain'], unique=False)
    op.create_index(op.f('ix_assets_content_rating'), 'assets', ['content_rating'], unique=False)
    op.create_index(op.f('ix_assets_last_accessed_at'), 'assets', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_assets_searchable'), 'assets', ['searchable'], unique=False)
    op.alter_column('provider_accounts', 'provider_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_accounts', 'provider_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_assets_searchable'), table_name='assets')
    op.drop_index(op.f('ix_assets_last_accessed_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_content_rating'), table_name='assets')
    op.drop_index(op.f('ix_assets_content_domain'), table_name='assets')
    op.drop_index(op.f('ix_assets_age_restricted'), table_name='assets')
    op.drop_column('assets', 'last_accessed_at')
    op.drop_column('assets', 'media_metadata')
    op.drop_column('assets', 'upload_method')
    op.drop_column('assets', 'original_source_url')
    op.drop_column('assets', 'searchable')
    op.drop_column('assets', 'age_restricted')
    op.drop_column('assets', 'content_rating')
    op.drop_column('assets', 'content_domain')
    op.drop_column('assets', 'embedding')
    op.drop_column('assets', 'style_tags')
    op.drop_column('assets', 'tags')
    op.drop_column('assets', 'description')
    op.drop_column('assets', 'mime_type')
    op.drop_column('assets', 'provider_uploads')
    op.drop_index(op.f('ix_asset_temporal_segments_asset_id'), table_name='asset_temporal_segments')
    op.drop_index('idx_segment_type', table_name='asset_temporal_segments')
    op.drop_index('idx_segment_asset_time', table_name='asset_temporal_segments')
    op.drop_table('asset_temporal_segments')
    op.drop_index('idx_audio_speech', table_name='asset_audio_metadata')
    op.drop_index('idx_audio_sample_rate', table_name='asset_audio_metadata')
    op.drop_index('idx_audio_codec', table_name='asset_audio_metadata')
    op.drop_table('asset_audio_metadata')
    op.drop_index('idx_adult_scene_type', table_name='asset_adult_metadata')
    op.drop_index('idx_adult_intimacy', table_name='asset_adult_metadata')
    op.drop_index('idx_adult_intensity_tempo', table_name='asset_adult_metadata')
    op.drop_table('asset_adult_metadata')
    op.drop_index('idx_3d_polygon_count', table_name='asset_3d_metadata')
    op.drop_index('idx_3d_format', table_name='asset_3d_metadata')
    op.drop_table('asset_3d_metadata')

    # Drop enum type
    contentdomain_enum = postgresql.ENUM('GENERAL', 'ADULT', 'MEDICAL', 'SPORTS', 'FASHION', 'EDUCATION', name='contentdomain')
    contentdomain_enum.drop(op.get_bind())
    # ### end Alembic commands ###
