"""Add content category and taxonomy fields

Revision ID: 14b1bebe4be1
Revises: 25b67935f5e1
Create Date: 2025-11-11 07:47:04.194821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '14b1bebe4be1'
down_revision = '25b67935f5e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('content_category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('assets', sa.Column('content_taxonomy', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_assets_content_category'), 'assets', ['content_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_content_category'), table_name='assets')
    op.drop_column('assets', 'content_taxonomy')
    op.drop_column('assets', 'content_category')
    # ### end Alembic commands ###
