"""add automation tables

Revision ID: 295075b0482d
Revises: 6f23b5e5a7ba
Create Date: 2025-11-13 01:51:13.537534

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '295075b0482d'
down_revision = '6f23b5e5a7ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_action_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('app_package', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('requires_password', sa.Boolean(), nullable=False),
    sa.Column('requires_google_account', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('continue_on_error', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['app_action_presets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_action_presets_category'), 'app_action_presets', ['category'], unique=False)
    op.create_index(op.f('ix_app_action_presets_id'), 'app_action_presets', ['id'], unique=False)
    op.create_index(op.f('ix_app_action_presets_is_shared'), 'app_action_presets', ['is_shared'], unique=False)
    op.create_index(op.f('ix_app_action_presets_is_system'), 'app_action_presets', ['is_system'], unique=False)
    op.create_index(op.f('ix_app_action_presets_owner_id'), 'app_action_presets', ['owner_id'], unique=False)
    op.create_table('android_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('device_type', sa.Enum('BLUESTACKS', 'ADB', name='devicetype'), nullable=False),
    sa.Column('connection_method', sa.String(length=20), server_default='adb', nullable=False),
    sa.Column('adb_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('device_serial', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('primary_device_id', sa.Integer(), nullable=True),
    sa.Column('instance_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('instance_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', 'ERROR', name='devicestatus'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('assigned_account_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_account_id'], ['provider_accounts.id'], ),
    sa.ForeignKeyConstraint(['primary_device_id'], ['android_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_android_devices_adb_id'), 'android_devices', ['adb_id'], unique=False)
    op.create_index(op.f('ix_android_devices_assigned_account_id'), 'android_devices', ['assigned_account_id'], unique=False)
    op.create_index(op.f('ix_android_devices_device_serial'), 'android_devices', ['device_serial'], unique=False)
    op.create_index(op.f('ix_android_devices_id'), 'android_devices', ['id'], unique=False)
    op.create_index(op.f('ix_android_devices_primary_device_id'), 'android_devices', ['primary_device_id'], unique=False)
    op.create_index(op.f('ix_android_devices_status'), 'android_devices', ['status'], unique=False)
    op.create_table('execution_loops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('preset_execution_mode', sa.Enum('SINGLE', 'SHARED_LIST', 'PER_ACCOUNT', name='presetexecutionmode'), nullable=False),
    sa.Column('shared_preset_ids', sa.JSON(), nullable=True),
    sa.Column('current_preset_index', sa.Integer(), nullable=False),
    sa.Column('account_preset_config', sa.JSON(), nullable=True),
    sa.Column('default_preset_ids', sa.JSON(), nullable=True),
    sa.Column('account_execution_state', sa.JSON(), nullable=True),
    sa.Column('selection_mode', sa.Enum('MOST_CREDITS', 'LEAST_CREDITS', 'ROUND_ROBIN', 'SPECIFIC_ACCOUNTS', name='loopselectionmode'), nullable=False),
    sa.Column('account_ids', sa.JSON(), nullable=True),
    sa.Column('min_credits', sa.Integer(), nullable=False),
    sa.Column('max_credits', sa.Integer(), nullable=True),
    sa.Column('require_online_device', sa.Boolean(), nullable=False),
    sa.Column('skip_accounts_already_ran_today', sa.Boolean(), nullable=False),
    sa.Column('skip_google_jwt_accounts', sa.Boolean(), nullable=False),
    sa.Column('delay_between_executions', sa.Integer(), nullable=False),
    sa.Column('max_executions_per_day', sa.Integer(), nullable=True),
    sa.Column('preferred_device_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', 'ERROR', name='loopstatus'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('last_account_id', sa.Integer(), nullable=True),
    sa.Column('executions_today', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preferred_device_id'], ['android_devices.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['app_action_presets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='automationstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('current_action_index', sa.Integer(), nullable=False),
    sa.Column('total_actions', sa.Integer(), nullable=False),
    sa.Column('screenshot_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_action_index', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('execution_context', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('loop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['provider_accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['android_devices.id'], ),
    sa.ForeignKeyConstraint(['loop_id'], ['execution_loops.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['app_action_presets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_account_id'), 'automation_executions', ['account_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_device_id'), 'automation_executions', ['device_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_id'), 'automation_executions', ['id'], unique=False)
    op.create_index(op.f('ix_automation_executions_preset_id'), 'automation_executions', ['preset_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_status'), 'automation_executions', ['status'], unique=False)
    op.create_index(op.f('ix_automation_executions_task_id'), 'automation_executions', ['task_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_user_id'), 'automation_executions', ['user_id'], unique=False)
    op.create_table('execution_loop_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('account_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('account_credits_before', sa.Integer(), nullable=True),
    sa.Column('account_credits_after', sa.Integer(), nullable=True),
    sa.Column('preset_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('selection_mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['provider_accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['android_devices.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.id'], ),
    sa.ForeignKeyConstraint(['loop_id'], ['execution_loops.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['app_action_presets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_loop_history_loop_id'), 'execution_loop_history', ['loop_id'], unique=False)
    # Note: intentionally excluding unrelated schema changes (e.g., generation_artifacts, enum/type tweaks, index changes)
    # to keep this migration focused on automation tables only.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_loop_history_loop_id'), table_name='execution_loop_history')
    op.drop_table('execution_loop_history')
    op.drop_index(op.f('ix_automation_executions_user_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_task_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_status'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_preset_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_device_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_account_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_table('execution_loops')
    op.drop_index(op.f('ix_android_devices_status'), table_name='android_devices')
    op.drop_index(op.f('ix_android_devices_primary_device_id'), table_name='android_devices')
    op.drop_index(op.f('ix_android_devices_id'), table_name='android_devices')
    op.drop_index(op.f('ix_android_devices_device_serial'), table_name='android_devices')
    op.drop_index(op.f('ix_android_devices_assigned_account_id'), table_name='android_devices')
    op.drop_index(op.f('ix_android_devices_adb_id'), table_name='android_devices')
    op.drop_table('android_devices')
    op.drop_index(op.f('ix_app_action_presets_owner_id'), table_name='app_action_presets')
    op.drop_index(op.f('ix_app_action_presets_is_system'), table_name='app_action_presets')
    op.drop_index(op.f('ix_app_action_presets_is_shared'), table_name='app_action_presets')
    op.drop_index(op.f('ix_app_action_presets_id'), table_name='app_action_presets')
    op.drop_index(op.f('ix_app_action_presets_category'), table_name='app_action_presets')
    op.drop_table('app_action_presets')
    # ### end Alembic commands ###
