"""add_generation_artifacts_and_remaining_schema_updates

Revision ID: 32e0c9501b5c
Revises: 576ebf8b59a6
Create Date: 2025-11-14 23:30:45.421782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32e0c9501b5c'
down_revision = '576ebf8b59a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Use existing operationtype enum
    operation_type_enum = postgresql.ENUM('TEXT_TO_VIDEO', 'IMAGE_TO_VIDEO', 'VIDEO_EXTEND', 'VIDEO_TRANSITION', 'FUSION', name='operationtype', create_type=False)

    op.create_table('generation_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', operation_type_enum, nullable=False),
    sa.Column('canonical_params', sa.JSON(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('reproducible_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_job_op', 'generation_artifacts', ['job_id', 'operation_type'], unique=False)
    op.create_index(op.f('ix_generation_artifacts_created_at'), 'generation_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_artifacts_job_id'), 'generation_artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_artifacts_operation_type'), 'generation_artifacts', ['operation_type'], unique=False)
    op.create_index(op.f('ix_generation_artifacts_reproducible_hash'), 'generation_artifacts', ['reproducible_hash'], unique=False)
    op.alter_column('asset_lineage', 'operation_type',
               existing_type=sa.VARCHAR(length=32),
               type_=operation_type_enum,
               nullable=False,
               postgresql_using='operation_type::operationtype')
    op.drop_index(op.f('idx_lineage_child_parent'), table_name='asset_lineage')
    op.create_index('idx_lineage_child_full', 'asset_lineage', ['child_asset_id', 'sequence_order'], unique=False)
    op.drop_index(op.f('idx_assets_style_tags_gin'), table_name='assets', postgresql_using='gin')
    op.drop_index(op.f('idx_assets_tags_gin'), table_name='assets', postgresql_using='gin')
    op.alter_column('jobs', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('idx_assets_tags_gin'), 'assets', [sa.literal_column('(tags::jsonb)')], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_assets_style_tags_gin'), 'assets', [sa.literal_column('(style_tags::jsonb)')], unique=False, postgresql_using='gin')
    op.drop_index('idx_lineage_child_full', table_name='asset_lineage')
    op.create_index(op.f('idx_lineage_child_parent'), 'asset_lineage', ['child_asset_id', 'parent_asset_id'], unique=False)
    op.alter_column('asset_lineage', 'operation_type',
               existing_type=sa.Enum('TEXT_TO_VIDEO', 'IMAGE_TO_VIDEO', 'VIDEO_EXTEND', 'VIDEO_TRANSITION', 'FUSION', name='operationtype'),
               type_=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_index(op.f('ix_generation_artifacts_reproducible_hash'), table_name='generation_artifacts')
    op.drop_index(op.f('ix_generation_artifacts_operation_type'), table_name='generation_artifacts')
    op.drop_index(op.f('ix_generation_artifacts_job_id'), table_name='generation_artifacts')
    op.drop_index(op.f('ix_generation_artifacts_created_at'), table_name='generation_artifacts')
    op.drop_index('idx_artifact_job_op', table_name='generation_artifacts')
    op.drop_table('generation_artifacts')
    # ### end Alembic commands ###
