"""
Game domain models

This module contains all game-related domain models that were consolidated
from the standalone game service into the main backend.
"""
from pixsim7.backend.main.domain.game.models import (
    GameScene,
    GameSceneNode,
    GameSceneEdge,
    GameSession,
    GameSessionEvent,
    GameLocation,
    GameNPC,
    NPCSchedule,
    NPCState,
)
from pixsim7.backend.main.domain.game.ecs import (
    get_npc_entity,
    set_npc_entity,
    get_npc_component,
    set_npc_component,
    update_npc_component,
    delete_npc_component,
    has_npc_component,
    list_npc_components,
    get_npc_tags,
    set_npc_tags,
    add_npc_tag,
    remove_npc_tag,
    get_npc_metadata,
    set_npc_metadata,
    update_npc_metadata,
    validate_entity,
    # Metric registry
    get_metric_registry,
    resolve_metric,
    get_npc_metric,
    set_npc_metric,
    update_npc_metric,
    list_metrics_for_category,
    get_metric_definition,
)
from pixsim7.backend.main.domain.game.game_state import (
    get_game_state,
    set_game_state,
    update_game_state,
    clear_game_state,
    is_in_mode,
    is_conversation_mode,
    is_scene_mode,
    is_room_mode,
    is_map_mode,
    is_menu_mode,
    get_focused_npc,
    get_active_narrative_program,
    get_current_location,
    get_current_scene,
)
from pixsim7.backend.main.domain.game.schemas import GameStateSchema

__all__ = [
    "GameScene",
    "GameSceneNode",
    "GameSceneEdge",
    "GameSession",
    "GameSessionEvent",
    "GameLocation",
    "GameNPC",
    "NPCSchedule",
    "NPCState",
    # ECS helpers
    "get_npc_entity",
    "set_npc_entity",
    "get_npc_component",
    "set_npc_component",
    "update_npc_component",
    "delete_npc_component",
    "has_npc_component",
    "list_npc_components",
    "get_npc_tags",
    "set_npc_tags",
    "add_npc_tag",
    "remove_npc_tag",
    "get_npc_metadata",
    "set_npc_metadata",
    "update_npc_metadata",
    "validate_entity",
    # Metric registry
    "get_metric_registry",
    "resolve_metric",
    "get_npc_metric",
    "set_npc_metric",
    "update_npc_metric",
    "list_metrics_for_category",
    "get_metric_definition",
    # Game state (Task 22)
    "GameStateSchema",
    "get_game_state",
    "set_game_state",
    "update_game_state",
    "clear_game_state",
    "is_in_mode",
    "is_conversation_mode",
    "is_scene_mode",
    "is_room_mode",
    "is_map_mode",
    "is_menu_mode",
    "get_focused_npc",
    "get_active_narrative_program",
    "get_current_location",
    "get_current_scene",
]
