"""Core game models and state management"""

from .models import (
    GameWorld,
    GameWorldState,
    GameSession,
    GameSessionEvent,
    GameLocation,
    GameScene,
    GameSceneNode,
    GameSceneEdge,
    GameNPC,
    NPCSchedule,
    NPCState,
    NpcExpression,
    GameHotspot,
)

from .ecs import (
    get_npc_entity,
    set_npc_entity,
    get_npc_component,
    set_npc_component,
    update_npc_component,
    delete_npc_component,
    has_npc_component,
    list_npc_components,
    get_npc_tags,
    set_npc_tags,
    add_npc_tag,
    remove_npc_tag,
    get_npc_metadata,
    set_npc_metadata,
    update_npc_metadata,
    validate_entity,
    get_metric_registry,
    resolve_metric,
    get_npc_metric,
    set_npc_metric,
    update_npc_metric,
    list_metrics_for_category,
    get_metric_definition,
    register_core_components,
)

from .game_state import (
    get_game_state,
    set_game_state,
    update_game_state,
    clear_game_state,
    is_in_mode,
    is_conversation_mode,
    is_scene_mode,
    is_room_mode,
    is_map_mode,
    is_menu_mode,
    get_focused_npc,
    get_active_narrative_program,
    get_current_location,
    get_current_scene,
)

__all__ = [
    # Models
    "GameWorld",
    "GameWorldState",
    "GameSession",
    "GameSessionEvent",
    "GameLocation",
    "GameScene",
    "GameSceneNode",
    "GameSceneEdge",
    "GameNPC",
    "NPCSchedule",
    "NPCState",
    "NpcExpression",
    "GameHotspot",
    # ECS
    "get_npc_entity",
    "set_npc_entity",
    "get_npc_component",
    "set_npc_component",
    "update_npc_component",
    "delete_npc_component",
    "has_npc_component",
    "list_npc_components",
    "get_npc_tags",
    "set_npc_tags",
    "add_npc_tag",
    "remove_npc_tag",
    "get_npc_metadata",
    "set_npc_metadata",
    "update_npc_metadata",
    "validate_entity",
    "get_metric_registry",
    "resolve_metric",
    "get_npc_metric",
    "set_npc_metric",
    "update_npc_metric",
    "list_metrics_for_category",
    "get_metric_definition",
    "register_core_components",
    # Game state
    "get_game_state",
    "set_game_state",
    "update_game_state",
    "clear_game_state",
    "is_in_mode",
    "is_conversation_mode",
    "is_scene_mode",
    "is_room_mode",
    "is_map_mode",
    "is_menu_mode",
    "get_focused_npc",
    "get_active_narrative_program",
    "get_current_location",
    "get_current_scene",
]
