"""
Device Agent model - for remote device connections
"""
from typing import Optional
from datetime import datetime
from sqlmodel import SQLModel, Field, Column
from sqlalchemy import Text


class DeviceAgent(SQLModel, table=True):
    """Remote device agent (user's machine running agent script)"""
    __tablename__ = "device_agents"

    id: Optional[int] = Field(default=None, primary_key=True, index=True)
    
    # Agent identification
    agent_id: str = Field(max_length=100, unique=True, index=True)  # UUID generated by agent
    name: str = Field(max_length=100)  # User-friendly name
    
    # Connection
    host: str = Field(max_length=100)  # IP address (ZeroTier IP)
    port: int = Field(default=5037)  # ADB port
    api_port: int = Field(default=8765)  # Agent API port for commands
    
    # Owner
    user_id: int = Field(foreign_key="users.id", index=True)
    
    # Status
    status: str = Field(max_length=20, default="offline", index=True)  # online, offline, error
    is_enabled: bool = Field(default=True)
    
    # Metadata
    last_heartbeat: Optional[datetime] = Field(default=None)
    version: Optional[str] = Field(default=None, max_length=20)  # Agent version
    os_info: Optional[str] = Field(default=None, max_length=100)  # OS details
    error_message: Optional[str] = Field(default=None, sa_column=Column(Text))
    
    # Timestamps
    created_at: Optional[datetime] = Field(default=None)
    updated_at: Optional[datetime] = Field(default=None)

    def __repr__(self) -> str:
        return f"<DeviceAgent {self.name} ({self.status})>"
