/**
 * UI Library
 *
 * Consolidated UI systems: overlays, composable panels, panel plugins, and display management.
 */

// ============================================================================
// Overlay System - On-screen overlay widgets
// ============================================================================
export {
  APIPresetStorage,
  BADGE_PRIORITY,
  BADGE_SLOT,
  BadgePresets,
  IndexedDBPresetStorage,
  LocalStoragePresetStorage,
  OverlayContainer,
  OverlayWidgetRenderer,
  PresetManager,
  SIZE_VALUES,
  SPACING_VALUES,
  TRANSITION_DURATIONS,
  VideoScrubWidgetRenderer,
  VisibilityStateMachine,
  WIDGET_Z_INDEX_RANGE,
  adaptVisibilityForTouch,
  applyDefaults,
  boundsOverlap,
  buildAddToSetWidget,
  buildCountBadgeWidget,
  buildOverlayConfigFromUnified,
  buildPinToggleWidget,
  buildRemoveWidget,
  buildSetIndicatorWidget,
  calculateAnchorPosition,
  calculateCustomPosition,
  calculatePosition,
  calculateWidgetBounds,
  combineClassNames,
  createBadgeWidget,
  createButtonWidget,
  createMenuWidget,
  createPanelWidget,
  createProgressWidget,
  createResolver,
  createSceneViewHost,
  createTooltipWidget,
  createUploadWidget,
  createVideoScrubWidget,
  extractPropertyPaths,
  filterWidgetsByGroup,
  fromUnifiedPosition,
  fromUnifiedSurfaceConfig,
  fromUnifiedVisibility,
  fromUnifiedWidget,
  getAdjacentAnchors,
  getDefaultMediaCardConfig,
  getInverseAnchor,
  getMediaCardPreset,
  getPathType,
  getTransitionClass,
  getTransitionStyle,
  groupWidgets,
  handleCollisions,
  isCustomPosition,
  isOverlayConfig,
  isOverlayPosition,
  isPositionSSRSafe,
  isPropertyPath,
  lintConfiguration,
  mediaCardPresets,
  mergeConfigurations,
  mergeMultipleConfigurations,
  mergeVisibilityConfig,
  mergeWidget,
  mergeWidgetStyle,
  mergeWidgets,
  normalizeOffset,
  partitionByStackGroup,
  pickWidgets,
  positionToStyle,
  prefersReducedMotion,
  presetManager,
  registerOverlayWidgets,
  removeWidgets,
  resolveCollisions,
  resolvePath,
  shouldShowWidget,
  suggestPathsForWidget,
  toCSSValue,
  toUnifiedSurfaceConfig,
  upsertWidgets,
  validateAnchor,
  validateAndLog,
  validateConfiguration,
  validatePosition,
  validateStyle,
  validateVisibilityConfig,
  validateWidget,
} from './overlay';
export type {
  APIStorageConfig,
  AddToSetWidgetOptions,
  BadgeWidgetConfig,
  ButtonWidgetConfig,
  Collision,
  CollisionResult,
  ComputedPosition,
  CountBadgeOptions,
  CustomPosition,
  MenuItem,
  MenuWidgetConfig,
  OverlayAnchor,
  OverlayConfiguration,
  OverlayContainerProps,
  OverlayPolicyStep,
  OverlayPosition,
  OverlayPreset,
  OverlayWidget,
  OverlayWidgetProps,
  PanelWidgetConfig,
  PartitionResult,
  PresetCapabilities,
  PresetCategory,
  PresetStorage,
  ProgressWidgetConfig,
  RemoveWidgetOptions,
  SceneViewHostConfig,
  SetIndicatorWidgetOptions,
  StackGroupInfo,
  TooltipContent,
  TooltipWidgetConfig,
  UploadState,
  UploadWidgetConfig,
  ValidationError,
  ValidationResult,
  VideoScrubWidgetConfig,
  VideoScrubWidgetRendererProps,
  VisibilityConfig,
  VisibilityTrigger,
  WidgetBounds,
  WidgetContext,
  WidgetPosition,
  WidgetSize,
  WidgetSpacing,
  WidgetStyle,
} from './overlay';

// ============================================================================
// Composer System - Grid-based panel composition
// ============================================================================
export {
  BlockRegistry,
  ComposedPanel,
  addBlock,
  addDataSource,
  addWidget,
  areBlocksInitialized,
  areWidgetsInitialized,
  blockRegistry,
  builtInBlocks,
  builtInWidgets,
  createComposition,
  demoCompositions,
  exportComposition,
  getDemoComposition,
  getDemoCompositionIds,
  importComposition,
  initializeBlocks,
  initializeWidgets,
  registerBuiltInBlocks,
  registerBuiltInWidgets,
  removeBlock,
  removeDataSource,
  removeWidget,
  updateBlock,
  updateWidget,
  useAvailableBlocks,
  useAvailableDataSources,
  validateComposition,
  widgetRegistry,
} from './composer';
export type {
  BlockConfigSchema,
  BlockDefinition,
  BlockInstance,
  BlockProps,
  BlockType,
  GridLayout,
  PanelComposition,
  WidgetDefinition,
  WidgetInstance,
  WidgetRegistry,
} from './composer';

// ============================================================================
// Panel System - Panel plugin registry and management
// ============================================================================
export {
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  PANEL_CATEGORIES,
  PanelHostLite,
  PanelPluginManager,
  PanelRegistry,
  ScopeHost,
  ScopeInstanceProvider,
  autoRegisterPanelGroups,
  definePanel,
  definePanelGroup,
  dockWidgetRegistry,
  dockWidgetSelectors,
  filterOpenSiblings,
  getDockWidget,
  getDockWidgetByDockviewId,
  getDockWidgetPanelIds,
  getInstanceId,
  getPanelContexts,
  getPanelIdsByTag,
  getPanelIdsForScope,
  getPanelsByTag,
  getPanelsForScope,
  initializePanels,
  panelActionRegistry,
  panelBelongsToContext,
  panelGroupRegistry,
  panelGroupSelectors,
  panelRegistry,
  panelSelectors,
  pluginManager,
  registerDefaultDockWidgets,
  registerDockWidget,
  registerSimplePanel,
  resolvePresetScope,
  resolveSettings,
  resolveSiblings,
  toPanelAction,
  toPanelActions,
  usePanelRegistryActions,
  useResolveAllComponentSettings,
  useResolveComponentSettings,
  useResolvePanelSettings,
  useScopeInstanceId,
} from '../../features/panels/lib';
export type {
  BasePanelDefinition,
  ContextLabelStrategy,
  CoreEditorRole,
  DefinePanelGroupOptions,
  DefinePanelOptions,
  DockWidgetDefinition,
  MutablePanelRegistryLike,
  PanelAction,
  PanelActionError,
  PanelActionsConfig,
  PanelAvailabilityPolicy,
  PanelCategory,
  PanelDefinition,
  PanelGroupDefinition,
  PanelGroupHostProps,
  PanelGroupLayoutConfig,
  PanelGroupModule,
  PanelGroupPreset,
  PanelInstancePolicy,
  PanelModule,
  PanelPlugin,
  PanelRegistryLike,
  PanelSlots,
  PanelTitleResolver,
  PresetScope,
  ResolvedSettings,
  ScopeHostProps,
  SiblingCandidate,
  ToPanelActionOptions,
  WorkspaceContext,
} from '../../features/panels/lib';

// ============================================================================
// Display System - Display space management
// ============================================================================
export { getDisplaySpacesFromWorldMeta, resolveDisplayTargetFromWorldMeta } from './display/displaySpaces';

// ============================================================================
// Prompt Companion Slot - Extension slot for prompt input surfaces
// ============================================================================
export {
  GlobalPromptCompanionInjector,
  PromptCompanionHost,
  PromptSurfaceProvider,
  promptCompanionEvents,
  promptCompanionRegistry,
  promptSurfaceRegistry,
  usePromptCompanionContext,
  usePromptCompanionEvents,
  usePromptCompanionSlot,
  usePromptSurface,
  usePromptSurfaceContext,
  useRegisterPromptCompanion,
} from './promptCompanionSlot';
export type {
  PromptCompanionContext,
  PromptCompanionEvent,
  PromptCompanionHostProps,
  PromptCompanionPlugin,
  PromptCompanionSurface,
  PromptSurfaceProviderProps,
  UsePromptSurfaceOptions,
  UsePromptSurfaceReturn,
} from './promptCompanionSlot';

// ============================================================================
// Form Components - Reusable form inputs
// ============================================================================
export { ArrayFieldInput } from './forms';
export type { ArrayFieldInputProps } from './forms';
