import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'node:path';

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: [
      // Domain-based path aliases (must come before generic '@' to take precedence)
      { find: '@/narrative', replacement: path.resolve(__dirname, '../../packages/game/engine/src/narrative') },
      { find: '@/scene', replacement: path.resolve(__dirname, '../../packages/game/engine/src/narrative') },
      { find: '@/gizmos', replacement: path.resolve(__dirname, './src/features/gizmos/lib/core') },
      { find: '@/types', replacement: path.resolve(__dirname, './src/types') },
      { find: '@app', replacement: path.resolve(__dirname, './src/app') },
      { find: '@domain', replacement: path.resolve(__dirname, './src/domain') },
      { find: '@shared/types', replacement: path.resolve(__dirname, '../../packages/shared/types/src') },
      // Lib modules - Core registries & systems
      { find: '@lib/core', replacement: path.resolve(__dirname, './src/lib/core') },
      { find: '@lib/shapes', replacement: path.resolve(__dirname, './src/lib/shapes') },
      { find: '@lib/api', replacement: path.resolve(__dirname, './src/lib/api') },
      // Lib modules - UI (consolidated)
      { find: '@lib/ui/panels', replacement: path.resolve(__dirname, './src/lib/ui/panels') },
      { find: '@lib/ui/composer', replacement: path.resolve(__dirname, './src/lib/ui/composer') },
      { find: '@lib/ui/overlay', replacement: path.resolve(__dirname, './src/lib/ui/overlay') },
      { find: '@lib/ui/display', replacement: path.resolve(__dirname, './src/lib/ui/display') },
      { find: '@lib/ui', replacement: path.resolve(__dirname, './src/lib/ui') },
      // Lib modules - Infrastructure
      { find: '@lib/generation-ui', replacement: path.resolve(__dirname, './src/lib/generation-ui') },
      { find: '@lib/utils', replacement: path.resolve(__dirname, './src/lib/utils') },
      { find: '@lib/auth', replacement: path.resolve(__dirname, './src/lib/auth') },
      { find: '@lib/theming', replacement: path.resolve(__dirname, './src/lib/theming') },
      { find: '@lib/game', replacement: path.resolve(__dirname, './src/lib/game') },
      { find: '@lib/hooks', replacement: path.resolve(__dirname, './src/lib/hooks') },
      { find: '@lib/analyzers', replacement: path.resolve(__dirname, './src/lib/analyzers') },
      { find: '@lib/context', replacement: path.resolve(__dirname, './src/lib/context') },
      { find: '@lib/dockview', replacement: path.resolve(__dirname, './src/lib/dockview') },
      { find: '@lib/dev/devtools', replacement: path.resolve(__dirname, './src/lib/dev/devtools') },
      { find: '@lib/dev/console', replacement: path.resolve(__dirname, './src/lib/dev/console') },
      { find: '@lib/dev', replacement: path.resolve(__dirname, './src/lib/dev') },
      { find: '@lib/plugins', replacement: path.resolve(__dirname, './src/lib/plugins') },
      { find: '@lib/assetProvider', replacement: path.resolve(__dirname, './src/lib/assetProvider') },
      { find: '@lib/registries', replacement: path.resolve(__dirname, './src/lib/registries.ts') },
      { find: '@lib/editing-core', replacement: path.resolve(__dirname, './src/lib/editing-core') },
      { find: '@lib/gameplay-ui-core', replacement: path.resolve(__dirname, './src/lib/gameplay-ui-core') },
      { find: '@lib/capabilities', replacement: path.resolve(__dirname, './src/lib/capabilities') },
      { find: '@lib/dataBinding', replacement: path.resolve(__dirname, './src/lib/dataBinding') },
      { find: '@lib/gating', replacement: path.resolve(__dirname, './src/lib/gating') },
      { find: '@lib/models', replacement: path.resolve(__dirname, './src/lib/models') },
      { find: '@lib/preview-bridge', replacement: path.resolve(__dirname, './src/lib/preview-bridge') },
      { find: '@lib/icons', replacement: path.resolve(__dirname, './src/lib/icons.tsx') },
      { find: '@lib/backendStorage', replacement: path.resolve(__dirname, './src/lib/backendStorage.ts') },
      { find: '@lib/nodeEditorRegistry', replacement: path.resolve(__dirname, './src/lib/nodeEditorRegistry.ts') },
      { find: '@lib/assetUrlResolver', replacement: path.resolve(__dirname, './src/lib/assetUrlResolver.ts') },
      // Feature modules
      { find: '@features/gizmos', replacement: path.resolve(__dirname, './src/features/gizmos') },
      { find: '@features/intimacy', replacement: path.resolve(__dirname, './src/features/intimacy') },
      { find: '@features/automation', replacement: path.resolve(__dirname, './src/features/automation') },
      { find: '@features/interactions', replacement: path.resolve(__dirname, './src/features/interactions') },
      { find: '@features/prompts', replacement: path.resolve(__dirname, './src/features/prompts') },
      { find: '@features/plugins', replacement: path.resolve(__dirname, './src/features/plugins') },
      { find: '@features/providers', replacement: path.resolve(__dirname, './src/features/providers') },
      { find: '@features/settings', replacement: path.resolve(__dirname, './src/features/settings') },
      { find: '@features/gallery', replacement: path.resolve(__dirname, './src/features/gallery') },
      { find: '@features/scene', replacement: path.resolve(__dirname, './src/features/scene') },
      { find: '@features/hud', replacement: path.resolve(__dirname, './src/features/hud') },
      { find: '@features/worldTools', replacement: path.resolve(__dirname, './src/features/worldTools') },
      { find: '@features/brainTools', replacement: path.resolve(__dirname, './src/features/brainTools') },
      { find: '@features/simulation', replacement: path.resolve(__dirname, './src/features/simulation') },
      { find: '@features/generation', replacement: path.resolve(__dirname, './src/features/generation') },
      { find: '@features/graph', replacement: path.resolve(__dirname, './src/features/graph') },
      { find: '@features/assets', replacement: path.resolve(__dirname, './src/features/assets') },
      { find: '@features/controlCenter', replacement: path.resolve(__dirname, './src/features/controlCenter') },
      { find: '@features/devtools', replacement: path.resolve(__dirname, './src/features/devtools') },
      { find: '@features/narrative', replacement: path.resolve(__dirname, './src/features/narrative') },
      { find: '@features/workspace', replacement: path.resolve(__dirname, './src/features/workspace') },
      { find: '@features/panels', replacement: path.resolve(__dirname, './src/features/panels') },
      { find: '@features/contextHub', replacement: path.resolve(__dirname, './src/features/contextHub') },
      { find: '@features/componentSettings', replacement: path.resolve(__dirname, './src/features/componentSettings') },
      { find: '@features/npcs', replacement: path.resolve(__dirname, './src/features/npcs') },
      // Workspace packages
      { find: '@pixsim7/scene.cubes', replacement: path.resolve(__dirname, '../../packages/scene/cubes/src') },
      // Local src directory alias for cleaner imports (must be last)
      { find: '@', replacement: path.resolve(__dirname, './src') },
    ],
  },
});
