/**
 * {{PLUGIN_NAME}} Session Helper Plugin
 * Generated by create-pixsim-plugin
 */

import type { GameSessionDTO } from '@pixsim7/types';
import { getFlag, setFlag } from '@pixsim7/game-core';

/**
 * Custom state interface for {{PLUGIN_NAME}}
 */
export interface {{PLUGIN_NAME_PASCAL}}State {
  // Define your state structure
  // Example:
  // value: number;
  // lastUpdated: number;
  // metadata?: Record<string, any>;
}

/**
 * {{PLUGIN_NAME}} session helper class
 *
 * This helper provides a clean API for managing {{PLUGIN_NAME}} state in the session.
 * All state is stored in session.flags under the '{{PLUGIN_ID}}' namespace.
 */
export class {{PLUGIN_NAME_PASCAL}}Helper {
  /**
   * Get {{PLUGIN_NAME}} state from session
   */
  static getState(session: GameSessionDTO): {{PLUGIN_NAME_PASCAL}}State | null {
    const state = getFlag(session, '{{PLUGIN_ID}}');
    return state || null;
  }

  /**
   * Set {{PLUGIN_NAME}} state (mutates session)
   */
  static setState(session: GameSessionDTO, state: {{PLUGIN_NAME_PASCAL}}State): void {
    setFlag(session, '{{PLUGIN_ID}}', state);
  }

  /**
   * Initialize {{PLUGIN_NAME}} state with defaults
   */
  static initialize(session: GameSessionDTO): void {
    if (!this.getState(session)) {
      this.setState(session, {
        // Set default state values
        // Example:
        // value: 0,
        // lastUpdated: Date.now(),
      });
    }
  }

  /**
   * Update a specific field in the state
   */
  static updateField<K extends keyof {{PLUGIN_NAME_PASCAL}}State>(
    session: GameSessionDTO,
    field: K,
    value: {{PLUGIN_NAME_PASCAL}}State[K]
  ): void {
    const state = this.getState(session);
    if (state) {
      state[field] = value;
      this.setState(session, state);
    }
  }

  /**
   * Check if {{PLUGIN_NAME}} is initialized
   */
  static isInitialized(session: GameSessionDTO): boolean {
    return this.getState(session) !== null;
  }

  /**
   * Reset {{PLUGIN_NAME}} state to defaults
   */
  static reset(session: GameSessionDTO): void {
    setFlag(session, '{{PLUGIN_ID}}', {
      // Reset to default values
    });
  }

  // Add more helper methods as needed
  // Example:
  // static incrementValue(session: GameSessionDTO, amount: number = 1): void {
  //   const state = this.getState(session);
  //   if (state) {
  //     state.value += amount;
  //     state.lastUpdated = Date.now();
  //     this.setState(session, state);
  //   }
  // }
}

/**
 * Extend the SessionHelpers interface for type safety
 * Add this declaration to your types file:
 *
 * declare module '@pixsim7/types' {
 *   interface SessionHelpers {
 *     {{PLUGIN_NAME_CAMEL}}: typeof {{PLUGIN_NAME_PASCAL}}Helper;
 *   }
 * }
 */
