/**
 * {{PLUGIN_NAME}} Interaction Plugin
 * Generated by create-pixsim-plugin
 */

import type {
  InteractionPlugin,
  BaseInteractionConfig,
  FormField,
  InteractionContext,
  InteractionResult,
} from '@pixsim7/types';

/**
 * Configuration for {{PLUGIN_NAME}} interaction
 */
export interface {{PLUGIN_NAME_PASCAL}}Config extends BaseInteractionConfig {
  enabled: boolean;
  // Add your custom config fields here
  // Example: maxAttempts: number;
}

/**
 * {{PLUGIN_NAME}} interaction plugin
 */
export const {{PLUGIN_NAME_CAMEL}}Plugin: InteractionPlugin<{{PLUGIN_NAME_PASCAL}}Config> = {
  id: '{{PLUGIN_ID}}',
  name: '{{PLUGIN_DISPLAY_NAME}}',
  description: '{{PLUGIN_DESCRIPTION}}',
  icon: '🔌', // Replace with your icon

  // Default configuration
  defaultConfig: {
    enabled: true,
    // Add default values for your custom fields
  },

  // Configuration form fields for UI
  configFields: [
    {
      key: 'enabled',
      label: 'Enabled',
      type: 'boolean',
      description: 'Enable or disable this interaction',
    },
    // Add more fields as needed:
    // {
    //   key: 'maxAttempts',
    //   label: 'Max Attempts',
    //   type: 'number',
    //   min: 1,
    //   max: 10,
    //   description: 'Maximum number of attempts allowed',
    // },
  ] as FormField[],

  // Main execution logic
  async execute(
    config: {{PLUGIN_NAME_PASCAL}}Config,
    context: InteractionContext
  ): Promise<InteractionResult> {
    const { state, api, session, onError, onSuccess } = context;

    try {
      // Your interaction logic here

      // Example: Access session data
      const inventory = session.getInventory();

      // Example: Update session state (optimistic)
      await session.addInventoryItem('example_item', 1);

      // Example: Show success message
      onSuccess('{{PLUGIN_DISPLAY_NAME}} executed successfully!');

      return {
        success: true,
        message: '{{PLUGIN_DISPLAY_NAME}} completed',
        data: { /* your result data */ },
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      onError(`{{PLUGIN_DISPLAY_NAME}} failed: ${message}`);

      return {
        success: false,
        message,
      };
    }
  },

  // Optional: Validate configuration
  validate(config: {{PLUGIN_NAME_PASCAL}}Config): string | null {
    // Add validation logic
    // Example:
    // if (config.maxAttempts < 1) {
    //   return 'Max attempts must be at least 1';
    // }
    return null;
  },

  // Optional: Check if interaction is available
  isAvailable(context: InteractionContext): boolean {
    // Add availability logic
    // Example: Only available if player has certain item
    // return context.session.getInventory().some(item => item.id === 'special_item');
    return true;
  },
};
