/**
 * {{PLUGIN_NAME}} Node Type Plugin
 * Generated by create-pixsim-plugin
 */

import type { NodeTypeDefinition } from '@pixsim7/types';

/**
 * Custom data structure for {{PLUGIN_NAME}} nodes
 */
export interface {{PLUGIN_NAME_PASCAL}}NodeData {
  // Add your custom node data fields
  // Example:
  // title: string;
  // content: string;
  // options?: Record<string, any>;
}

/**
 * {{PLUGIN_NAME}} node type definition
 */
export const {{PLUGIN_NAME_CAMEL}}NodeType: NodeTypeDefinition<{{PLUGIN_NAME_PASCAL}}NodeData> = {
  id: '{{PLUGIN_ID}}',
  name: '{{PLUGIN_DISPLAY_NAME}}',
  description: '{{PLUGIN_DESCRIPTION}}',
  icon: '🔲', // Replace with your icon
  category: 'custom', // Change to: 'media' | 'flow' | 'logic' | 'action' | 'custom'
  scope: 'scene', // Optional: 'scene' | 'arc' | 'world' | 'custom' - for multi-level organization

  // Default data when creating a new node of this type
  defaultData: {
    // Set default values for your custom fields
    // Example:
    // title: 'New {{PLUGIN_DISPLAY_NAME}}',
    // content: '',
  },

  // JSON schema for validation (optional)
  schema: {
    type: 'object',
    properties: {
      // Define your schema
      // Example:
      // title: { type: 'string', minLength: 1 },
      // content: { type: 'string' },
    },
    // required: ['title'],
  },

  // Component names for lazy loading
  editorComponent: '{{PLUGIN_NAME_PASCAL}}Editor', // Implement in frontend
  rendererComponent: '{{PLUGIN_NAME_PASCAL}}Renderer', // Implement in frontend

  // Custom validation function (optional)
  validate(data: {{PLUGIN_NAME_PASCAL}}NodeData): string | null {
    // Add custom validation logic
    // Example:
    // if (!data.title || data.title.trim() === '') {
    //   return 'Title is required';
    // }
    return null;
  },

  // Whether this node can be added via UI (default: true)
  userCreatable: true,

  // UI styling hints
  color: '#3b82f6', // Border/text color
  bgColor: '#eff6ff', // Background color

  // Lazy loading (optional) - useful for heavy plugins
  // loader: async () => {
  //   const module = await import('./{{PLUGIN_ID}}.full');
  //   return module.{{PLUGIN_NAME_CAMEL}}NodeType;
  // },

  // Preload priority (optional) - higher = load sooner
  // preloadPriority: 5, // 0-10, default 0
};
