/**
 * {{PLUGIN_NAME}} Node Renderer Plugin
 * Generated by create-pixsim-plugin
 */

import type { NodeRenderer, NodeRendererProps } from '@/lib/graph/nodeRendererRegistry';

/**
 * Custom data interface for this node type
 */
interface {{PLUGIN_NAME_PASCAL}}NodeData {
  // Define the data structure this renderer expects
  // Example:
  // title: string;
  // content: string;
  // metadata?: Record<string, any>;
}

/**
 * {{PLUGIN_NAME}} Node Renderer Component
 */
export function {{PLUGIN_NAME_PASCAL}}Renderer({
  node,
  isSelected,
  isStart,
  hasErrors,
}: NodeRendererProps) {
  // Cast node data to your custom type
  const data = node as unknown as {{PLUGIN_NAME_PASCAL}}NodeData;

  return (
    <div className="px-3 py-3 space-y-2">
      {/* Header Section */}
      <div className="flex items-center gap-2">
        <span className="text-2xl">🔲</span> {/* Replace with your icon */}
        <div className="text-sm font-medium text-neutral-700 dark:text-neutral-200">
          {{PLUGIN_DISPLAY_NAME}}
        </div>
      </div>

      {/* Content Section */}
      <div className="space-y-1">
        {/* Add your rendering logic here */}
        {/* Example:
        <div className="text-sm font-semibold">{data.title}</div>
        <div className="text-xs text-neutral-600 dark:text-neutral-400">
          {data.content}
        </div>
        */}
      </div>

      {/* Status Indicators */}
      {isSelected && (
        <div className="text-xs text-blue-600 dark:text-blue-400">
          Selected
        </div>
      )}

      {hasErrors && (
        <div className="text-xs text-red-600 dark:text-red-400">
          Has validation errors
        </div>
      )}

      {isStart && (
        <div className="inline-flex items-center gap-1 px-2 py-0.5 bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 rounded text-xs font-medium">
          <span>▶</span> Start Node
        </div>
      )}
    </div>
  );
}

/**
 * Register the renderer
 */
export const {{PLUGIN_NAME_CAMEL}}Renderer: NodeRenderer = {
  nodeType: '{{PLUGIN_ID}}',
  component: {{PLUGIN_NAME_PASCAL}}Renderer,
  defaultSize: {
    width: 250,
    height: 150,
  },
  customHeader: false, // Set to true if you want full control over the node appearance

  // Lazy loading (optional) - useful for heavy renderer components
  // loader: async () => {
  //   const module = await import('./{{PLUGIN_ID}}.renderer.full');
  //   return module.{{PLUGIN_NAME_PASCAL}}Renderer;
  // },

  // Preload priority (optional) - higher = load sooner
  // preloadPriority: 5, // 0-10, default 0
};
