/**
 * Smart Dockview
 *
 * Lightweight dockview infrastructure with:
 * - Local (feature-scoped) panel registries
 * - Smart tab visibility (tabs shown only when 2+ panels grouped)
 * - Layout persistence
 * - Minimal chrome styling
 */

export { SmartDockview } from './SmartDockview';
export type { SmartDockviewProps } from './SmartDockview';

// Shared utilities (re-exported from shared packages)
export {
  LocalPanelRegistry,
  createLocalPanelRegistry,
  configurePanelLookup,
  useSmartDockview,
  useDockviewIds,
  createSafeApi,
  createDockviewHost,
  resolveDockview,
  resolveDockviewApi,
  resolveDockviewHost,
  addDockviewPanel,
  ensurePanels,
  getDockviewGroupCount,
  getDockviewGroups,
  getDockviewPanels,
  findDockviewPanel,
  focusPanel,
  isPanelOpen,
  resolvePanelDefinitionId,
  getDockviewHost,
  getDockviewHostIds,
  getDockviewApi,
  getDockviewCapabilities,
  getDockviewRegistration,
  getAllDockviewHosts,
  registerDockviewHost,
  unregisterDockviewHost,
  subscribeToDockviewRegistry,
  dockZoneRegistry,
  registerDockZone,
  unregisterDockZone,
  getDockZone,
  getDockZoneByDockviewId,
  resolvePresetScope,
  setDefaultPresetScope,
  getDefaultPresetScope,
  getDockZonePanelIds,
  registerDefaultDockZones,
  areDefaultZonesRegistered,
  DEFAULT_DOCK_ZONES,
} from '@pixsim7/shared.ui.dockview';

export type {
  UseSmartDockviewOptions,
  UseSmartDockviewReturn,
  DockviewIds,
  SafeDockviewApi,
  DockviewHost,
  ResolveDockviewResult,
  AddDockviewPanelOptions,
  EnsurePanelsOptions,
  DockviewCapabilities,
  DockviewRegistration,
  DockZoneDefinition,
  PresetScope,
  LocalPanelDefinition,
  PanelPosition,
  PanelSizeConstraints,
  SmartDockviewConfig,
  SmartDockviewLayout,
  SmartDockviewPanelProps,
} from '@pixsim7/shared.ui.dockview';

// Context menu system
export {
  ContextMenuPortal,
  ContextMenuProvider,
  ContextMenuRegistry,
  CustomTabComponent,
  DockviewIdProvider,
  PanelPropertiesPopup,
  PropertiesPopup,
  addPanelAction,
  addPanelActions,
  allActions,
  assetActions,
  autoContextConfigRegistry,
  buildDockviewContext,
  closeAllInGroupAction,
  closeOtherPanelsAction,
  closePanelAction,
  contextDataCache,
  contextDataRegistry,
  contextHubActions,
  contextMenuAttrs,
  contextMenuIgnore,
  contextMenuRegistry,
  cubeActions,
  debugActions,
  deletePresetAction,
  extractContextFromElement,
  floatPanelAction,
  focusPanelAction,
  getAllProviders,
  getCapability,
  getDefaultScopePanelSubmenu,
  getEditQuickAddActions,
  getQuickAddActions,
  getRegistryChain,
  getScopeLabel,
  hasCapability,
  hasLiveState,
  joinLeftGroupAction,
  joinRightGroupAction,
  layoutActions,
  loadPresetAction,
  maximizePanelAction,
  menuActionsToCapabilityActions,
  movePanelAction,
  moveToNewGroupAction,
  panelActionDefinitions,
  panelActions,
  panelPropertiesAction,
  pinTabAction,
  presetActionDefinitions,
  presetActions,
  propertiesAction,
  quickAddActionDefinitions,
  quickAddActions,
  registerContextMenuActions,
  registerPanelActionCapabilities,
  registerPresetActionCapabilities,
  registerQuickAddActionCapabilities,
  resetLayoutAction,
  resolveCurrentDockview,
  resolveCurrentDockviewApi,
  resolveProvider,
  restorePanelAction,
  savePresetAction,
  splitDownAction,
  splitPanelAction,
  splitRightAction,
  toMenuAction,
  toMenuActions,
  unpinTabAction,
  useAssetAutoContextMenu,
  useAutoContextMenu,
  useComponentContextMenu,
  useContextMenu,
  useContextMenuItem,
  useContextMenuOptional,
  useDockviewContext,
  useDockviewId,
  usePromptAutoContextMenu,
  usePropertiesPopupStore,
  useRegisterContextData,
} from './contextMenu';
export type {
  AppContextMenuServices,
  AutoContextConfig,
  ComponentContextMenuResult,
  ContextDataResolver,
  ContextMenuAttrs,
  ContextMenuContext,
  ContextMenuContextBase,
  ContextMenuContextValue,
  DockviewLayout,
  DockviewContextBase,
  DockviewContextOverrides,
  LayoutPreset,
  MenuAction,
  MenuActionBase,
  MenuActionContext,
  MenuActionContextBase,
  MenuItem,
  PanelRegistryLike,
  ProviderEntry,
  RegistryScope,
  ToMenuActionOptions,
  UseComponentContextMenuOptions,
} from './contextMenu';

export {
  FLOATING_HOST_CONTEXT_PAYLOAD_KEY,
  FLOATING_ORIGIN_META_KEY,
  buildFloatingOriginMetaRecord,
  deriveFloatingGroupRestoreHint,
  readFloatingHostContextPayload,
  readFloatingOriginMeta,
  removePanelAndPruneEmptyGroup,
  setFloatingHostContextPayload,
  stripFloatingOriginMeta,
} from './floatingPanelInterop';
export type {
  FloatingGroupRestoreDirection,
  FloatingGroupRestoreHint,
  FloatingOriginMeta,
} from './floatingPanelInterop';
